# Generated by Django 3.2 on 2021-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'обработанный'), ('unprocessed', 'необработанный')], default='unprocessed', max_length=20),
        ),
    ]
