# Generated by Django 3.2 on 2021-11-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20211126_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method_of_payment',
            field=models.CharField(choices=[('cash', 'наличностью'), ('card', 'электронно')], default='cash', max_length=20),
        ),
    ]
